title: Gray Mint Moon
email: your-email@domain.com
description: > 
  Gray Mint Moon thrives in helping holistic entrepreneurs fulfill
  their business missions by providing web development
  and design services.
mission: We are passionate about creating intuitive and beautiful websites for holistic entrepreneurs to increase their business and attract clients who appreciate the core soul of their brand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_username: graymintmoon
keywords: gray mint moon, web development service, holistic health website, holistic health web development, web design service, wordpress developer, custom web design, affordable web development

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
